### ISSUE TITLE
Convert specific file via CLI

### ISSUE THREAD

**Issue by TheChymera** [BrkRaw/brkraw#142]
```console
[deco]~ ❱ brkraw -v
brkraw v0.3.10
[deco]~ ❱ brkraw tonii -o lala.nii.gz /usr/share/opfvta_brudata/20170411_120358_5682_1_4/8/pdata/1/2dseq
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/brkraw", line 33, in <module>
    sys.exit(load_entry_point('brkraw==0.3.10', 'console_scripts', 'brkraw')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/brkraw/scripts/brkraw.py", line 152, in main
    study    = BrukerLoader(path)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/brkraw/lib/loader.py", line 104, in __init__
    self._pvobj = load(path)
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/brkraw/lib/loader.py", line 31, in load
    raise FileNotValidError(path, DataType.PVDATASET)
brkraw.lib.errors.FileNotValidError: (PosixPath('/usr/share/opfvta_brudata/20170411_120358_5682_1_4/8/pdata/1/2dseq'), <DataType.PVDATASET: 1>)
```

It's a bit confusing that this does not work, and instead I need to use the `--scanid` and `--recoid` parameters from which the path then gets constructed, when it would be more transparent to just use the path explicitly.

Would you be interested in supporting this?

**Comment by dvm-shlee** [comment]
@TheChymera The core module for handling individual files has been developed. Apologies for the delay.

The updated version includes a new script called 'brk_tonifti', which addresses the cases you mentioned. It supports loading entire study directories, scan directories, reco directories, or even individual files like '2dseq', 'visu_pars', etc. The internal Python API is complete, and we expect the script files and documentation to be ready by mid-May. Significant changes have been made to the API.

To indicate that this project has been addressed, I've marked this issue in the pull request concerning the updated API.

All new code has been added as a separate module under both the API and the app, ensuring that the current version's functionality remains unaffected.
