### ISSUE TITLE
tonii_all crashes if run against a bruker study directory

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/brkraw#27]
Works fine if I run it properly on the parent directory, however crashes if I run against a single study (I know this is not the right way to do it, but it shouldn't crash)
```
$ brkraw tonii_all 20200707_CIC_PLANTEST_007.321/
Traceback (most recent call last):
  File "/home/gdevenyi/miniforge3/bin/brkraw", line 8, in <module>
    sys.exit(main())
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/scripts/brkraw.py", line 210, in main
    study = BrukerLoader(sub_path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/loader.py", line 89, in __init__
    self._pvobj = load(path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/loader.py", line 17, in load
    return PvDatasetDir(path)
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 145, in __init__
    self._parse_info()
  File "/home/gdevenyi/miniforge3/lib/python3.7/site-packages/brkraw/lib/pvobj.py", line 160, in _parse_info
    if len(root.split(os.sep)) == root_path_fregs + 1:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

**Comment by dvm-shlee** [comment]
@gdevenyi Oh this is a good point, it was my bad habit just make occur the error when unexpected execution, I will make it to print message instead for the next version.

**Comment by dvm-shlee** [comment]
@gdevenyi FYI, I updated you as the author for this project since your contributions to refining the module a huge! Thank you a lot! Actually the progression on revising the module and paper is slowed due to the recent busy days but will let you know soon.
I may ask for some advice from you related to the testing module development once I prepared the platform for it.

**Comment by gdevenyi** [comment]
:+1:

Thank you for the inclusion! I guess I'll have to sling some code now to justify that :)

**Comment by dvm-shlee** [comment]
the new update I made on the pull request will solve this issue.
not sure when it happened, but the code generates an error if the folder is not pvdataobj, which is the opposite condition of what I originally intended to (to make only works for the parents folder)

I will close this issue
